spring:
  application:
    name: banana
  datasource: 
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 3001 #端口号

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:2001/eureka/ 